version: "2"

services:
  linksnatch:
    image: ghcr.io/obiequack/linksnatch-docker:main
    container_name: linksnatch
    ports:
      - 3000:3000
    networks:
      - main
    volumes:
      - ./app:/app/linksnatch

networks:
  main: